"""change data type to chat_id and hour fields on alarm

Revision ID: 1432bbb0f487
Revises: 7c84c190c820
Create Date: 2016-10-27 00:24:36.386239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1432bbb0f487'
down_revision = '7c84c190c820'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
