"""change data type to chat_id and hour fields on alarm

Revision ID: 5635e1857fbe
Revises: 623f55fb03d3
Create Date: 2016-10-27 00:23:36.762708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5635e1857fbe'
down_revision = '623f55fb03d3'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarms', 'hour')
    op.drop_column('alarms', 'chat_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarms', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('alarms', sa.Column('hour', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
