"""Adding repeat field on alarms

Revision ID: 5881f65eb492
Revises: a1a211001094
Create Date: 2016-10-26 23:53:27.628017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5881f65eb492'
down_revision = 'a1a211001094'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarms', sa.Column('repeat', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarms', 'repeat')
    ### end Alembic commands ###
