"""Adding admin and banned fields on users

Revision ID: a1a211001094
Revises: 0ca84a6b1929
Create Date: 2016-10-26 20:44:35.162759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a211001094'
down_revision = '0ca84a6b1929'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('banned', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banned')
    op.drop_column('users', 'admin')
    ### end Alembic commands ###
